### ISSUE TITLE
Unable to install pods

### ISSUE THREAD

**Issue by rajdhakate** [myoungsc/SCCardView#1]
unable to install through pods. throws error `[!] Unable to find a specification for 'SCCardView'`

here's the log - 

Preparing

Analyzing dependencies

Inspecting targets to integrate
  Using `ARCHS` setting to build architectures of target `Pods-Test`: (``)

Resolving dependencies of `Podfile`
[!] Unable to find a specification for `SCCardView`

/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/lib/cocoapods/resolver.rb:461:in 'handle_resolver_error'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/lib/cocoapods/resolver.rb:80:in 'rescue in resolve'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/lib/cocoapods/resolver.rb:72:in 'resolve'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/lib/cocoapods/installer/analyzer.rb:742:in 'block in resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/lib/cocoapods/user_interface.rb:64:in 'section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/lib/cocoapods/installer/analyzer.rb:739:in 'resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/lib/cocoapods/installer/analyzer.rb:76:in 'analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/lib/cocoapods/installer.rb:236:in 'analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/lib/cocoapods/installer.rb:150:in 'block in resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/lib/cocoapods/user_interface.rb:64:in 'section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/lib/cocoapods/installer.rb:149:in 'resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/lib/cocoapods/installer.rb:110:in 'install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/lib/cocoapods/command/install.rb:41:in 'run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.1/lib/claide/command.rb:334:in 'run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/bin/pod:55:in '<top (required)>'
/usr/local/bin/pod:23:in 'load'
/usr/local/bin/pod:23:in '< main >'

**Comment by myoungsc** [comment]
hi rajdhakate
Run the following commands in the terminal, then install the pod again 

```ruby
pod repo remove master
pod setup
pod install
```

All the best,
myoung

**Comment by rajdhakate** [comment]
Yes now working. thanks
